#!/usr/bin/env bun
// Generates the missing Tailwind @theme registration for the v2 design
// tokens. Unlike the v1 tokens (script/tailwind.ts, sourced from a
// hand-maintained colors.txt), the v2 tokens in v2/styles/colors.css and
// v2/styles/theme.css were defined but never wired into Tailwind's @theme
// system -- every `bg-v2-*`/`text-v2-*`/etc utility class was silently a
// no-op. This scans those two files directly for `--v2-<name>:` custom
// property declarations and emits a `--color-v2-<name>: var(--v2-<name>)`
// mapping for each, so Tailwind's JIT can generate the corresponding
// utilities. Deliberately does NOT reset `--color-*: initial` (unlike the
// v1 generator) -- both files are imported into the same cascade, and
// resetting here would wipe out the v1 color registrations too.

const root = import.meta.dir + "/../src/v2/styles"
const sources = [await Bun.file(root + "/colors.css").text(), await Bun.file(root + "/theme.css").text()]

const names = new Set<string>()
for (const source of sources) {
  for (const match of source.matchAll(/--v2-[\w-]+(?=\s*:)/g)) {
    names.add(match[0].slice(2))
  }
}

const variables = [...names].sort().map((name) => `--color-${name}: var(--${name});`)

const output = `
/* Generated by script/tailwind-v2.ts */
/* Do not edit this file manually */

@theme {
  ${variables.join("\n  ")}
}
`

await Bun.file(root + "/tailwind-colors.css").write(output.trim())
